"""
backend/routers/structural.py
Structural engineering assessment API endpoints — Phase 2.

Endpoints:
    GET  /structural/{district_id}                       → per-asset structural load, SF, damage state
    GET  /structural/{district_id}/hardening-priority    → ranked pre-landfall reinforcement list
    POST /structural/{district_id}/assess                → trigger fresh structural assessment
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/structural", tags=["structural"])


# ── Response models ─────────────────────────────────────────────────────────

class AssetStructuralResult(BaseModel):
    asset_id: str
    asset_class: str
    wind_speed_kmh: float
    surge_height_m: float
    safety_factor: float
    likely_failure: bool
    reinforcement_advisable: bool
    combined_expected_damage_state: str
    confidence: str
    hardening_priority_score: float
    notes: list[str]


class HardeningItem(BaseModel):
    rank: int
    asset_id: str
    asset_class: str
    safety_factor: float
    hardening_priority_score: float
    combined_expected_damage_state: str
    recommended_action: str
    confidence: str
    likely_failure: bool
    notes: list[str]


class StructuralAssessmentResponse(BaseModel):
    district_id: str
    event_id: str
    wind_speed_kmh: float
    assets: list[AssetStructuralResult]
    total_at_risk: int
    likely_failure_count: int
    reinforcement_advisable_count: int


class HardeningPriorityResponse(BaseModel):
    district_id: str
    event_id: str
    wind_speed_kmh: float
    items: list[HardeningItem]
    disclaimer: str = (
        "This is a screening-level priority list generated by a parametric model. "
        "It is NOT a substitute for a licensed structural engineer's site assessment. "
        "Fragility parameters marked 'generic_curve' have not been calibrated to "
        "Bay of Bengal construction stock."
    )


# ── Demo data generator ─────────────────────────────────────────────────────

def _demo_asset_list(district_id: str) -> list[dict]:
    """Generate representative demo asset list for a district."""
    return [
        {"asset_id": f"{district_id}-POLE-001",  "asset_class": "wood_power_pole",   "criticality": 0.7},
        {"asset_id": f"{district_id}-POLE-002",  "asset_class": "concrete_power_pole","criticality": 0.75},
        {"asset_id": f"{district_id}-TOWER-001", "asset_class": "steel_lattice_tower","criticality": 0.9},
        {"asset_id": f"{district_id}-HOSP-001",  "asset_class": "hospital",           "criticality": 0.95},
        {"asset_id": f"{district_id}-SHLT-001",  "asset_class": "shelter",            "criticality": 0.85},
        {"asset_id": f"{district_id}-RCC-001",   "asset_class": "rcc_building",       "criticality": 0.6},
        {"asset_id": f"{district_id}-MAS-001",   "asset_class": "masonry_building",   "criticality": 0.5},
        {"asset_id": f"{district_id}-THATCH-001","asset_class": "thatched_roof_house","criticality": 0.4},
    ]


def _demo_surge_grid(asset_list: list[dict], max_surge_m: float) -> dict[str, float]:
    """Assign representative surge heights (varies by asset type)."""
    surge_scale = {
        "wood_power_pole": 0.4, "concrete_power_pole": 0.3,
        "steel_lattice_tower": 0.2, "hospital": 0.5,
        "shelter": 0.3, "rcc_building": 0.6,
        "masonry_building": 0.7, "thatched_roof_house": 0.9,
    }
    return {
        asset["asset_id"]: round(max_surge_m * surge_scale.get(asset["asset_class"], 0.5), 2)
        for asset in asset_list
    }


# ── Route handlers ───────────────────────────────────────────────────────────

@router.get("/{district_id}", response_model=StructuralAssessmentResponse)
async def get_structural_assessment(
    district_id: str,
    event_id: str = Query("FANI-2019", description="Cyclone event identifier"),
    wind_speed_kmh: float = Query(220.0, description="Forecast max 1-min wind speed [km/h]"),
    max_surge_m: float = Query(3.5, description="Max surge inundation height [m]"),
) -> StructuralAssessmentResponse:
    """
    Return per-asset structural load, safety factor, and damage state predictions
    for all infrastructure assets in the district.
    """
    try:
        from modeling.structural_engineering.damage_state import assess_asset_damage_state  # type: ignore[import]

        asset_list = _demo_asset_list(district_id)
        surge_grid = _demo_surge_grid(asset_list, max_surge_m)

        asset_results = []
        for asset in asset_list:
            sa = assess_asset_damage_state(
                asset_id=asset["asset_id"],
                asset_class=asset["asset_class"],
                wind_speed_kmh=wind_speed_kmh,
                surge_height_m=surge_grid.get(asset["asset_id"], 0.0),
                criticality=asset.get("criticality", 0.5),
            )
            asset_results.append(
                AssetStructuralResult(
                    asset_id=sa.asset_id,
                    asset_class=sa.asset_class,
                    wind_speed_kmh=sa.wind_speed_kmh,
                    surge_height_m=sa.surge_height_m,
                    safety_factor=sa.safety_factor,
                    likely_failure=sa.likely_failure,
                    reinforcement_advisable=sa.reinforcement_advisable,
                    combined_expected_damage_state=sa.combined_expected_damage_state,
                    confidence=sa.confidence,
                    hardening_priority_score=sa.hardening_priority_score,
                    notes=sa.notes,
                )
            )

        return StructuralAssessmentResponse(
            district_id=district_id,
            event_id=event_id,
            wind_speed_kmh=wind_speed_kmh,
            assets=asset_results,
            total_at_risk=len(asset_results),
            likely_failure_count=sum(1 for a in asset_results if a.likely_failure),
            reinforcement_advisable_count=sum(1 for a in asset_results if a.reinforcement_advisable),
        )

    except Exception as exc:
        logger.exception("Structural assessment failed for district %s.", district_id)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/{district_id}/hardening-priority", response_model=HardeningPriorityResponse)
async def get_hardening_priority(
    district_id: str,
    event_id: str = Query("FANI-2019"),
    wind_speed_kmh: float = Query(220.0),
    max_surge_m: float = Query(3.5),
    top_n: int = Query(20, ge=1, le=100, description="Return top N assets by priority"),
) -> HardeningPriorityResponse:
    """
    Return ranked pre-landfall reinforcement priority list for the district.
    """
    try:
        from modeling.structural_engineering.hardening_priority import (  # type: ignore[import]
            run_district_hardening_assessment,
        )

        asset_list = _demo_asset_list(district_id)
        surge_grid = _demo_surge_grid(asset_list, max_surge_m)

        recommendations = run_district_hardening_assessment(
            asset_list=asset_list,
            wind_speed_kmh=wind_speed_kmh,
            surge_grid=surge_grid,
        )

        items = [
            HardeningItem(
                rank=r.rank,
                asset_id=r.asset_id,
                asset_class=r.asset_class,
                safety_factor=r.safety_factor,
                hardening_priority_score=r.hardening_priority_score,
                combined_expected_damage_state=r.combined_expected_damage_state,
                recommended_action=r.recommended_action,
                confidence=r.confidence,
                likely_failure=r.likely_failure,
                notes=r.notes,
            )
            for r in recommendations[:top_n]
        ]

        return HardeningPriorityResponse(
            district_id=district_id,
            event_id=event_id,
            wind_speed_kmh=wind_speed_kmh,
            items=items,
        )

    except Exception as exc:
        logger.exception("Hardening priority failed for district %s.", district_id)
        raise HTTPException(status_code=500, detail=str(exc))
