import { useState } from 'react'
import type { AdvisoryOut } from '../api/client'

interface Props {
  advisory: AdvisoryOut
  onDispatch: () => void
}

export default function AdvisoryPreview({ advisory, onDispatch }: Props) {
  const [tab, setTab] = useState<'en' | 'local'>('en')

  const severityClass = advisory.severity_tier === 'Evacuation Order'
    ? 'evacuation'
    : advisory.severity_tier.toLowerCase()

  return (
    <div className="panel-section fade-in" id="advisory-panel">
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
        <div className="panel-label" style={{ marginBottom: 0 }}>AI-Generated Advisory</div>
        <span className={`severity-badge ${severityClass}`}>{advisory.severity_tier}</span>
        {advisory.validation_passed && (
          <span className="severity-badge safe">✓ Validated</span>
        )}
      </div>

      {/* Validation warnings */}
      {advisory.validation_warnings.length > 0 && (
        <div style={{
          background: 'rgba(249,115,22,0.1)',
          border: '1px solid rgba(249,115,22,0.3)',
          borderRadius: 'var(--radius-sm)',
          padding: '6px 10px',
          fontSize: 10,
          color: 'var(--color-warning)',
          marginBottom: 8,
        }}>
          ⚠️ {advisory.validation_warnings.length} ungrounded number(s) detected. Review before dispatch.
        </div>
      )}

      {/* Language tabs */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 8 }}>
        <button
          id="tab-advisory-en"
          className={`btn btn-sm ${tab === 'en' ? 'btn-primary' : 'btn-ghost'}`}
          onClick={() => setTab('en')}
        >
          English
        </button>
        <button
          id="tab-advisory-local"
          className={`btn btn-sm ${tab === 'local' ? 'btn-primary' : 'btn-ghost'}`}
          onClick={() => setTab('local')}
        >
          ଓଡ଼ିଆ (Odia)
        </button>
      </div>

      <div className="advisory-box" id="advisory-content">
        {tab === 'en' ? advisory.content_en : advisory.content_local}
      </div>

      <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
        <button
          id="btn-dispatch-advisory"
          className="btn btn-danger"
          style={{ flex: 1, justifyContent: 'center' }}
          onClick={onDispatch}
          disabled={advisory.status === 'dispatched'}
        >
          {advisory.status === 'dispatched'
            ? '✅ Dispatched'
            : '🚨 Confirm & Dispatch'}
        </button>
      </div>

      <div style={{ fontSize: 9, color: 'var(--color-text-muted)', marginTop: 6 }}>
        Generated by {advisory.generated_by} · Status: {advisory.status}
      </div>
    </div>
  )
}
